#!/bin/bash
read -p "Enter name:" name
whitespace='              '
if [[ $name =~ [A-Z] ]]
then
name=$(echo $name | tr [:upper:] [:lower:])
fi
k=0
for((i=${#name};i>0;i-=1))
do
name3=""
if [[ $i == ${#name} ]]
then
name1="${name:0:i}"
for((j=${#name1};j>1;j-=1))
do
name2="${name1:j-2:1}"
name3=$name3$name2
done
else
name1="${name:1:(${#name}-2)}"
fi
echo "${whitespace:0:$k}""$name1""$name3"
name=$name1$name3
k=$k+1
done
